Repository dnd-side-project/dnd-5th-10-frontend, pull requests merged in 2021-08, with the labels that each got.

#12 Feature/9 social login
  package-lock.json
  package.json
  src/components/Cookies.js
  src/components/LoginModal.js
  src/components/Navigation.js
  src/constants/Oauth.js
  src/index.js
  src/pages/Main.js
Labels: enhancement

#13 Feature/11 question register
  jsconfig.json
  public/img/questionRegister.jpg
  src/App.js
  src/Routes/Routers.js
  src/components/ClassificationTags.css
  src/components/ClassificationTags.js
  src/components/LoginModal.js
  src/components/MainCarousel.js
  src/components/Navigation.js
  src/components/QuestionRegister.css
  src/components/QuestionRegister.js
  src/components/Tags.css
  src/components/Tags.js
  src/pages/Main.js
  src/pages/MainPage.js
  src/pages/QuestionRegisterPage.js
Labels: enhancement

#17 Feature/14 set quiz options
  src/Routes/Routers.js
  src/components/SetQuizOptions.js
  src/components/Tags.js
  src/constants/TagItems.js
  src/css/SetQuizOptions.css
  src/pages/MainPage.js
  src/pages/QuizPage.js
Labels: enhancement

#23 Feature/21 footer UI
  src/Routes/Routers.js
  src/components/Footer.js
  src/constants/TagItems.js
  src/css/Footer.css
Labels: enhancement

#30 Feature/29 style width
  src/App.css
  src/components/Footer.js
  src/components/QuestionRegister.js
  src/components/QuestionSearch.js
  src/components/SetQuizOptions.js
  src/css/ClassificationTags.css
  src/css/Footer.css
  src/css/MyBookmarkQuestion.css
  src/css/MyLikeAnswer.css
  src/css/MyPage.css
  src/css/MyRegisterAnswer.css
  src/css/MyRegisterQuestion.css
  src/css/Navigation.css
  src/css/Question.css
  src/css/QuestionRegister.css
  src/css/QuestionSearch.css
  src/css/SetQuizOptions.css
  src/css/Tags.css
  src/pages/MainPage.js
  src/pages/QuestionRegisterPage.js
  src/pages/QuestionSearchPage.js
  src/pages/QuizPage.js
Labels: style

#40 Feature/39 quiz page
  public/img/quiz_img.png
  src/components/QuizResult.js
  src/components/QuizSolving.js
  src/components/SetQuizOptions.js
  src/css/QuizResult.css
  src/css/QuizSolving.css
  src/css/SetQuizOptions.css
  src/pages/SetQuizOptionsPage.js
Labels: enhancement, style

#47 Feature/45 answer register
  src/Routes/Routers.js
  src/components/AnswerRegister.js
  src/components/Question.js
  src/css/AnswerRegister.css
  src/pages/AnswerRegisterPage.js
Labels: enhancement

#50 Feature/41 login modal UI
  public/img/github-logo.png
  public/img/login_img.png
  src/components/LoginModal.js
  src/components/Navigation.js
  src/css/LoginModal.css
  src/css/Navigation.css
Labels: style

#53 Feature/52 question register style
  src/components/QuestionRegister.js
  src/css/QuestionRegister.css
  src/pages/QuestionRegisterPage.js
Labels: enhancement, style

#58 style: 전역폰트는 나눔스퀘어, 메인폰트는 나눔스퀘어 라운드로 수정
  src/App.css
  src/css/MainCarousel.css
Labels: style

#57 Feature/55 modify quiz UI
  src/components/Question.js
  src/components/QuizResult.js
  src/components/QuizSolving.js
  src/components/SetQuizOptions.js
  src/css/QuizResult.css
  src/css/SetQuizOptions.css
  src/pages/SetQuizOptionsPage.js
Labels: enhancement, style

#60 Feature/44 main page bottom
  src/css/MainPage.css
  src/pages/MainPage.js
Labels: enhancement, style
